version: '3.4'

services:
    webstatus:
        container_name: webstatus
        image: ${DOCKER_REGISTRY-}webstatus
        build:
            context: .
            dockerfile: src/WebApps/WebStatus/Docker/Dotnet70/Dockerfile
        ports:
            - 8006:80
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - HealthChecksUI__HealthChecks__0__Name=Product API Health Check
            - HealthChecksUI__HealthChecks__0__Uri=http://product-api/health/ready
            - HealthChecksUI__HealthChecks__1__Name=Basket API Health Check
            - HealthChecksUI__HealthChecks__1__Uri=http://basket-api/health/ready
            - HealthChecksUI__HealthChecks__2__Name=Discount API Health Check
            - HealthChecksUI__HealthChecks__2__Uri=http://discount-api/health/ready
            - HealthChecksUI__HealthChecks__3__Name=Order API Health Check
            - HealthChecksUI__HealthChecks__3__Uri=http://order-api/health/ready
            - HealthChecksUI__HealthChecks__4__Name=Shopping Aggregator Health Check
            - HealthChecksUI__HealthChecks__4__Uri=http://shopping-aggregator/health/ready
            - HealthChecksUI__HealthChecks__5__Name=Shopping Web APP Health Check
            - HealthChecksUI__HealthChecks__5__Uri=http://shopping-webapp/health/ready
            - HealthChecksUI__HealthChecks__6__Name=Authentication API Health Check
            - HealthChecksUI__HealthChecks__6__Uri=http://authentication-api/health/ready
