version: '3.4'

services:
    rabbitmq:
        container_name: rabbitmq
        restart: always
        ports:
            - "5672:5672"
            - "15672:15672"

    catalog-mongo:
        container_name: catalog-mongo
        restart: always
        ports:
            - "27017:27017"
        volumes:
            - catalog-mongo:/data/db

    catalog-mongo-client:
        container_name: catalog-mongo-client
        depends_on:
            - catalog-mongo
        ports:
            - "3000:3000"

    catalog-api:
        container_name: catalog-api
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - "DatabaseSettings:ConnectionString=mongodb://catalog-mongo:27017"
        depends_on:
            - catalog-mongo
        ports:
            - "8000:80"

    basket-redis:
        container_name: basket-redis
        restart: always
        ports:
            - "6379:6379"

    basket-api:
        container_name: basket-api
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - "CacheSettings:ConnectionString=basket-redis:6379"
            - "DiscountGrpcSettings:DiscountUrl=http://discount-grpc"
        depends_on:
            - basket-redis
            - discount-grpc
            - rabbitmq
        ports:
            - "8001:80"

    discount-postgres:
        container_name: discount-postgres
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin1234
            - POSTGRES_DB=DiscountDB
        restart: always
        ports:
            - "5432:5432"
        volumes:
            - discount-postgres:/var/lib/postgresql/data

    discount-pgadmin:
        container_name: discount-pgadmin
        environment:
            - PGADMIN_DEFAULT_EMAIL=admin@aspdotnetcore.com
            - PGADMIN_DEFAULT_PASSWORD=admin1234
        restart: always
        depends_on:
            - discount-postgres
        ports:
            - "5050:80"
        volumes:
            - discount-pgadmin:/root/.pgadmin

    discount-api:
        container_name: discount-api
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
        depends_on:
            - discount-postgres
        ports:
            - "8002:80"

    discount-grpc:
        container_name: discount-grpc
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - "DatabaseSettings:Host=discount-postgres"
        depends_on:
            - discount-postgres
        ports:
            - "8003:80"

    order-mssql:
        container_name: order-mssql
        environment:
            - "MSSQL_SA_PASSWORD=Admin^1234"
            - "ACCEPT_EULA=Y"
        restart: always
        ports:
            - "1433:1433"

    order-api:
        container_name: order-api
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
        depends_on:
            - order-mssql
            - rabbitmq
        ports:
            - "8004:80"

    ocelot-api-gateway:
        container_name: ocelot-api-gateway
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
        depends_on:
            - catalog-api
            - basket-api
            - discount-api
            - order-api
        ports:
            - "8010:80"

    shopping-aggregator:
        container_name: shopping-aggregator
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
        depends_on:
            - catalog-api
            - basket-api
            - order-api
        ports:
            - "8005:80"

    shopping-webapp:
        container_name: shopping-webapp
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
        depends_on:
            - ocelot-api-gateway
        ports:
            - "8080:80"

    authentication-mssql:
        container_name: authentication-mssql
        environment:
            - "MSSQL_SA_PASSWORD=Admin^1234"
            - "ACCEPT_EULA=Y"
        restart: always
        ports:
            - "14330:1433"

    authentication-api:
        container_name: authentication-api
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
        depends_on:
            - authentication-mssql
        ports:
            - "8088:80"
