version: '3.4'

services:
    rabbitmq:
        image: rabbitmq:3.12.7-management-alpine

    product-mongo:
        image: ${DOCKER_REGISTRY-}product-mongo
        build:
            context: .
            dockerfile: src/Services/Product/Product.API/Docker/Mongo60/Dockerfile

    product-mongo-client:
        image: ${DOCKER_REGISTRY-}product-mongo-client
        build:
            context: .
            dockerfile: src/Services/Product/Product.API/Docker/MongoClient40/Dockerfile

    product-api:
        image: ${DOCKER_REGISTRY-}product-api
        build:
            context: .
            dockerfile: src/Services/Product/Product.API/Docker/DotNet70/Dockerfile

    basket-redis:
        image: ${DOCKER_REGISTRY-}basket-redis
        build:
            context: .
            dockerfile: src/Services/Basket/Basket.API/Docker/Redis72/Dockerfile

    basket-api:
        image: ${DOCKER_REGISTRY-}basket-api
        build:
            context: .
            dockerfile: src/Services/Basket/Basket.API/Docker/DotNet70/Dockerfile

    discount-postgres:
        image: ${DOCKER_REGISTRY-}discount-postgres
        build:
            context: .
            dockerfile: src/Services/Discount/Discount.API/Docker/Postgres16/Dockerfile

    discount-pgadmin:
        image: ${DOCKER_REGISTRY-}discount-pgadmin
        build:
            context: .
            dockerfile: src/Services/Discount/Discount.API/Docker/PgAdmin77/Dockerfile

    discount-api:
        image: ${DOCKER_REGISTRY-}discount-api
        build:
            context: .
            dockerfile: src/Services/Discount/Discount.API/Docker/DotNet70/Dockerfile

    discount-grpc:
        image: ${DOCKER_REGISTRY-}discount-grpc
        build:
            context: .
            dockerfile: src/Services/Discount/Discount.Grpc/Docker/DotNet70/Dockerfile

    order-mssql:
        image: ${DOCKER_REGISTRY-}order-mssql
        build:
            context: .
            dockerfile: src/Services/Order/Order.Rest/Docker/MicrosoftSQLServer2022-20/Dockerfile

    order-api:
        image: ${DOCKER_REGISTRY-}order-api
        build:
            context: .
            dockerfile: src/Services/Order/Order.Rest/Docker/Dotnet70/Dockerfile

    ocelot-api-gateway:
        image: ${DOCKER_REGISTRY-}ocelot-apigateway
        build:
            context: .
            dockerfile: src/ApiGateways/OcelotApiGateway/Docker/Dotnet70/Dockerfile

    shopping-aggregator:
        image: ${DOCKER_REGISTRY-}shopping-aggregator
        build:
            context: .
            dockerfile: src/ApiGateways/Shopping.Aggregator/Docker/Dotnet70/Dockerfile

    shopping-webapp:
        image: ${DOCKER_REGISTRY-}shopping-webapp
        build:
            context: .
            dockerfile: src/WebApps/Shopping.WebApp/Docker/Dotnet70/Dockerfile

    authentication-mssql:
        image: ${DOCKER_REGISTRY-}authentication-mssql
        build:
            context: .
            dockerfile: src/Services/Authentication/Authentication.API/Docker/MicrosoftSQLServer2022-20/Dockerfile

    authentication-api:
        image: ${DOCKER_REGISTRY-}authentication-api
        build:
            context: .
            dockerfile: src/Services/Authentication/Authentication.API/Docker/Dotnet70/Dockerfile

volumes:
    product-mongo:
        name: product-mongo
    discount-postgres:
        name: discount-postgres
    discount-pgadmin:
        name: discount-pgadmin

