version: '3.4'

services:
    rabbitmq:
        image: rabbitmq:3.12.7-management-alpine
        container_name: rabbitmq
        restart: always
        ports:
            - "5672:5672"
            - "15672:15672"
