version: '3.4'

services:
    catalog.api.mongo:
        image: ${DOCKER_REGISTRY-}catalog-mongo
        build:
            context: .
            dockerfile: Services/Catalog/Catalog.API/Docker/Mongo60/Dockerfile.image

    catalog.api.mongo.client:
        image: ${DOCKER_REGISTRY-}catalog-mongo-client
        build:
            context: .
            dockerfile: Services/Catalog/Catalog.API/Docker/MongoClient40/Dockerfile.image

    catalog.api:
        image: ${DOCKER_REGISTRY-}catalog-api
        build:
            context: .
            dockerfile: Services/Catalog/Catalog.API/Docker/DotNet70/Dockerfile.image

    basket.api.redis:
        image: ${DOCKER_REGISTRY-}basket-redis
        build:
            context: .
            dockerfile: Services/Basket/Basket.API/Docker/Redis72/Dockerfile.image

    basket.api:
        image: ${DOCKER_REGISTRY-}basket-api
        build:
            context: .
            dockerfile: Services/Basket/Basket.API/Docker/DotNet70/Dockerfile.image

    discount.api.postgres:
        image: ${DOCKER_REGISTRY-}discount-postgres
        build:
            context: .
            dockerfile: Services/Basket/Discount.API/Docker/Postgres16/Dockerfile.image

    discount.api.pgadmin:
        image: ${DOCKER_REGISTRY-}discount-pgadmin
        build:
            context: .
            dockerfile: Services/Basket/Discount.API/Docker/PgAdmin77/Dockerfile.image

    discount.api:
        image: ${DOCKER_REGISTRY-}discount-api
        build:
            context: .
            dockerfile: Services/Discount/Discount.API/Docker/DotNet70/Dockerfile.image

volumes:
    catalog.api.mongo:
        name: catalog-api-mongo
    discount.api.postgres:
        name: discount-api-postgres
    discount.api.pgadmin:
        name: discount-api-pgadmin
