version: '3.4'

services:
    portainer:
        image: portainer/portainer-ce:2.19.1
        container_name: portainer
        restart: always
        ports:
            - "8081:8000"
            - "9000:9000"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - portainer_data:/data

volumes:
    portainer_data:
