version: '3.4'

services:
    catalog.api.mongo:
        container_name: catalog-api-mongo
        restart: always
        ports:
            - "27017:27017"
        volumes:
            - catalog.api.mongo:/data/db

    catalog.api.mongo.client:
        container_name: catalog-api-mongo-client
        depends_on:
            - catalog.api.mongo
        ports:
            - "3000:3000"

    catalog.api:
        container_name: catalog-api
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - "DatabaseSettings:ConnectionString=mongodb://catalog-api-mongo:27017"
        depends_on:
            - catalog.api.mongo
        ports:
            - "8000:80"

    basket.api.redis:
        container_name: basket-api-redis
        restart: always
        ports:
            - "6379:6379"

    basket.api:
        container_name: basket-api
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - "CacheSettings:ConnectionString=basket-api-redis:6379"
        depends_on:
            - basket.api.redis
        ports:
            - "8001:80"
