version: '3.4'

services:
    rabbitmq:
        image: rabbitmq:3.12.7-management-alpine

    catalog.api.mongo:
        image: ${DOCKER_REGISTRY-}catalog-mongo
        build:
            context: .
            dockerfile: Services/Catalog/Catalog.API/Docker/Mongo60/Dockerfile.image

    catalog.api.mongo.client:
        image: ${DOCKER_REGISTRY-}catalog-mongo-client
        build:
            context: .
            dockerfile: Services/Catalog/Catalog.API/Docker/MongoClient40/Dockerfile.image

    catalog.api:
        image: ${DOCKER_REGISTRY-}catalog-api
        build:
            context: .
            dockerfile: Services/Catalog/Catalog.API/Docker/DotNet70/Dockerfile.image

    basket.api.redis:
        image: ${DOCKER_REGISTRY-}basket-redis
        build:
            context: .
            dockerfile: Services/Basket/Basket.API/Docker/Redis72/Dockerfile.image

    basket.api:
        image: ${DOCKER_REGISTRY-}basket-api
        build:
            context: .
            dockerfile: Services/Basket/Basket.API/Docker/DotNet70/Dockerfile

    discount.api.postgres:
        image: ${DOCKER_REGISTRY-}discount-postgres
        build:
            context: .
            dockerfile: Services/Discount/Discount.API/Docker/Postgres16/Dockerfile.image

    discount.api.pgadmin:
        image: ${DOCKER_REGISTRY-}discount-pgadmin
        build:
            context: .
            dockerfile: Services/Discount/Discount.API/Docker/PgAdmin77/Dockerfile.image

    discount.api:
        image: ${DOCKER_REGISTRY-}discount-api
        build:
            context: .
            dockerfile: Services/Discount/Discount.API/Docker/DotNet70/Dockerfile.image

    discount.grpc:
        image: ${DOCKER_REGISTRY-}discount-grpc
        build:
            context: .
            dockerfile: Services/Discount/Discount.Grpc/Docker/DotNet70/Dockerfile.image

    order.api.mssql:
        image: ${DOCKER_REGISTRY-}order-mssql
        build:
            context: .
            dockerfile: Services/Order/Order.Rest/Docker/MicrosoftSQLServer2022-20/Dockerfile

    order.api:
        image: ${DOCKER_REGISTRY-}order-api
        build:
            context: .
            dockerfile: Services/Order/Order.Rest/Docker/Dotnet70/Dockerfile

    ocelot.api.gateway:
        image: ${DOCKER_REGISTRY-}ocelot-apigateway
        build:
            context: .
            dockerfile: ApiGateways/OcelotApiGateway/Docker/Dotnet70/Dockerfile

volumes:
    catalog.api.mongo:
        name: catalog-api-mongo
    discount.api.postgres:
        name: discount-api-postgres
    discount.api.pgadmin:
        name: discount-api-pgadmin

