apiVersion: apps/v1
kind: Deployment
metadata:
    name: product-api-deployment
    labels:
        app: product-api
spec:
    replicas: 1
    selector:
        matchLabels:
            app: product-api
    template:
        metadata:
            labels:
                app: product-api
        spec:
            containers:
                -
                    name: product-api
                    image: 'janvodak/shoppingapp-product-api:latest'
                    imagePullPolicy: IfNotPresent
                    ports:
                        -
                            containerPort: 80
                    resources:
                        requests:
                            memory: 64Mi
                            cpu: 250m
                        limits:
                            memory: 128Mi
                            cpu: 500m
                    env:
                        -
                            name: ASPNETCORE_ENVIRONMENT
                            value: Development
                        -
                            name: DatabaseSettings__ConnectionString
                            valueFrom:
                                configMapKeyRef:
                                    name: mongo-configmap
                                    key: connection_string
