apiVersion: v1
kind: Service
metadata:
    name: product-api-service
spec:
    type: NodePort
    selector:
        app: product-api
    ports:
        -
            protocol: TCP
            port: 8000
            targetPort: 80
            nodePort: 31000
